import {
  int,
  mysqlEnum,
  mysqlTable,
  text,
  timestamp,
  varchar,
  decimal,
  boolean,
  json,
} from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 * Extended with role-based access control for managers and mechanic.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  phone: varchar("phone", { length: 20 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["manager", "mechanic", "admin"]).default("manager").notNull(),
  branchName: varchar("branchName", { length: 255 }), // For managers only
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Bike types with pricing for each branch
 * Created by branch managers, shared across the system
 */
export const bikeTypes = mysqlTable("bike_types", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(), // e.g., "Dراجة أطفال"
  nameEn: varchar("nameEn", { length: 255 }), // English name
  nameFr: varchar("nameFr", { length: 255 }), // French name
  price: int("price").notNull(), // Price in cents (e.g., 1000 for 10€)
  createdBy: int("createdBy").notNull(), // Manager ID who created it
  isActive: boolean("isActive").default(true).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type BikeType = typeof bikeTypes.$inferSelect;
export type InsertBikeType = typeof bikeTypes.$inferInsert;

/**
 * Orders from branch managers to mechanic
 * Contains list of bikes to be assembled
 */
export const orders = mysqlTable("orders", {
  id: int("id").autoincrement().primaryKey(),
  orderNumber: varchar("orderNumber", { length: 50 }).notNull().unique(), // Unique order ID (e.g., ORD-20250108-001)
  managerId: int("managerId").notNull(), // Branch manager who created the order
  branchName: varchar("branchName", { length: 255 }).notNull(),
  status: mysqlEnum("status", ["pending", "in_progress", "completed"]).default("pending").notNull(),
  bikes: json("bikes").notNull(), // JSON array: [{bikeTypeId, quantity, barcode}, ...]
  notes: text("notes"), // Optional notes from manager
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  completedAt: timestamp("completedAt"),
});

export type Order = typeof orders.$inferSelect;
export type InsertOrder = typeof orders.$inferInsert;

/**
 * Invoices generated by mechanic after completing orders
 */
export const invoices = mysqlTable("invoices", {
  id: int("id").autoincrement().primaryKey(),
  invoiceNumber: varchar("invoiceNumber", { length: 50 }).notNull().unique(), // Auto-generated (e.g., INV-20250108-001)
  orderId: int("orderId").notNull(), // Reference to order
  mechanicId: int("mechanicId").notNull(), // Mechanic who created invoice
  managerId: int("managerId").notNull(), // Branch manager
  branchName: varchar("branchName", { length: 255 }).notNull(),
  items: json("items").notNull(), // JSON array: [{bikeTypeName, quantity, unitPrice, total}, ...]
  totalAmount: int("totalAmount").notNull(), // Total in cents
  paymentMethod: varchar("paymentMethod", { length: 100 }), // e.g., "Bank Transfer", "Cash"
  invoiceDate: timestamp("invoiceDate").defaultNow().notNull(),
  pdfUrl: varchar("pdfUrl", { length: 500 }), // S3 URL to PDF
  pdfKey: varchar("pdfKey", { length: 255 }), // S3 key for reference
  status: mysqlEnum("status", ["draft", "sent", "paid"]).default("draft").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Invoice = typeof invoices.$inferSelect;
export type InsertInvoice = typeof invoices.$inferInsert;

/**
 * Notifications for real-time updates
 * Push notifications for order and invoice events
 */
export const notifications = mysqlTable("notifications", {
  id: int("id").autoincrement().primaryKey(),
  recipientId: int("recipientId").notNull(), // User receiving notification
  type: mysqlEnum("type", ["order_created", "order_completed", "invoice_sent", "invoice_paid"]).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  body: text("body"),
  relatedOrderId: int("relatedOrderId"), // Optional reference to order
  relatedInvoiceId: int("relatedInvoiceId"), // Optional reference to invoice
  isRead: boolean("isRead").default(false).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type Notification = typeof notifications.$inferSelect;
export type InsertNotification = typeof notifications.$inferInsert;

/**
 * Order items tracking (bikes scanned during assembly)
 * Used to track progress of order completion
 */
export const orderItems = mysqlTable("order_items", {
  id: int("id").autoincrement().primaryKey(),
  orderId: int("orderId").notNull(),
  bikeTypeId: int("bikeTypeId").notNull(),
  quantity: int("quantity").notNull(),
  completedQuantity: int("completedQuantity").default(0).notNull(),
  barcodes: json("barcodes").notNull(), // JSON array of scanned barcodes: [{barcode, scannedAt}, ...]
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type OrderItem = typeof orderItems.$inferSelect;
export type InsertOrderItem = typeof orderItems.$inferInsert;

/**
 * Audit log for tracking all important actions
 */
export const auditLog = mysqlTable("audit_log", {
  id: int("id").autoincrement().primaryKey(),
  userId: int("userId").notNull(),
  action: varchar("action", { length: 100 }).notNull(), // e.g., "order_created", "invoice_sent"
  entityType: varchar("entityType", { length: 50 }).notNull(), // e.g., "order", "invoice"
  entityId: int("entityId").notNull(),
  details: json("details"), // Additional context
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type AuditLog = typeof auditLog.$inferSelect;
export type InsertAuditLog = typeof auditLog.$inferInsert;
